class Buffer:
    def __init__(self):
        self.agent1_state = []
        self.agent2_state = []
        self.agent1_next_state = []
        self.agent2_next_state = []
        self.agent1_qvalue = []
        self.agent2_qvalue = []
        self.agent1_nvalue = []
        self.agent2_nvalue = []
        self.agent1_reward = []
        self.agent2_reward = []
        self.agent1_mean = []
        self.agent2_mean = []
        self.agent1_loss = []
        self.agent2_loss = []
        self.agent1_actions = []
        self.agent2_actions = []
        self.loss = []
        self.episodes = []
        self.returns = []
        self.agent1_qmean = []
        self.agent2_qmean = []
        self.agent1_nqmean = []
        self.agent2_nqmean = []
        self.agent1_meanloss = []
        self.agent2_meanloss = []
        self.meanloss = []
        self.agent1_mean_policy = []
        self.agent2_mean_policy = []
        self.agent1_policy = []
        self.agent2_policy = []
        
        
